import {Characters} from 'collections/characters';

export function loadCharacters() {
  if (Characters.find().count() === 0) {

    var characters = [
        {
						"firstName": "Bill",
						"middleName": "",
						"lastName": "Murray",
						"title": "King",
						"race": "Human",
						"sex": "male",
						"heightM": 1,
						"heightCm": 90,
						"weight": 91,
						"description": "A dude",
      			"hp" : 15,
						"str": 15,
						"int": 13,
						"wis": 18,
						"con": 15,
						"dex": 15,
						"cha": 18,
						"willTab": 0,
						"strTab": 0,
						"intTab": 0,
						"wisTab": 0,
						"conTab": 0,
						"dexTab": 0,
						"chaTab": 0,
						"hitRoll": 0,
						"hitRollTab": 0,
						"reflex": 0,
						"fortitude": 0,
						"will": 0,
						"reflexTab": 0,
						"fortitudeTab": 0,
						"level0": 0,
						"level1": 0,
						"level2": 0,
						"level3": 0,
						"level4": 0,
						"level5": 0,
						"level6": 0,
						"level7": 0,
						"level8": 0,
						"level9": 0,
						"level0Tab": 0,
						"level1Tab": 0,
						"level2Tab": 0,
						"level3Tab": 0,
						"level4Tab": 0,
						"level5Tab": 0,
						"level6Tab": 0,
						"level7Tab": 0,
						"level8Tab": 0,
						"level9Tab": 0,
						"backstory": "backstory yay",
						"spells": [],
						"skills": [
								{
										"name": "Rock",
										"level": "10",
										"stat": "str",
										"tab": 0
								}
						],
						"feats": [],
						"damage": 1,
						"hpBonus": 0,
						"strBonus": 0,
						"intBonus": 0,
						"wisBonus": 0,
						"conBonus": 0,
						"dexBonus": 0,
						"chaBonus": 0,
						"hitRollBonus": 0,
						"reflexBonus": 0,
						"fortitudeBonus": 0,
						"willBonus": 0,
						"level0Bonus": 0,
						"level1Bonus": 0,
						"level2Bonus": 0,
						"level3Bonus": 0,
						"level4Bonus": 0,
						"level5Bonus": 0,
						"level6Bonus": 0,
						"level7Bonus": 0,
						"level8Bonus": 0,
						"level9Bonus": 0,
						"alignment": "Lawful Good",
						"deity": "Pelor",
						"bronze": 0,
						"silver": 0,
						"gold": 0,
						"inventory": "nothing",
						"ac": 0,
						"acBonus": 0,
						"evade": 0,
						"evadeBonus": 0,
						"age": 31,
						"birthday": "December 10",
						"block": 0,
						"movement": 2,
						"movementBonus": 0,
						"level0Exhausted": 100,
						"level1Exhausted": 100,
						"level2Exhausted": 100,
						"level3Exhausted": 100,
						"level4Exhausted": 100,
						"level5Exhausted": 100,
						"level6Exhausted": 100,
						"level7Exhausted": 100,
						"level8Exhausted": 100,
						"level9Exhausted": 100,
						"level0Fail": 99,
						"level0FailBonus": 0,
						"level1Fail": 99,
						"level1FailBonus": 0,
						"level2Fail": 99,
						"level2FailBonus": 0,
						"level3Fail": 99,
						"level3FailBonus": 0,
						"level4Fail": 99,
						"level4FailBonus": 0,
						"level5Fail": 99,
						"level5FailBonus": 0,
						"level6Fail": 99,
						"level6FailBonus": 0,
						"level7Fail": 99,
						"level7FailBonus": 0,
						"level8Fail": 99,
						"level8FailBonus": 0,
						"level9Fail": 99,
						"level9FailBonus": 0              
				}
    ];

    for (var i = 0; i < characters.length; i++) {
        Characters.insert(characters[i]);
    }
  }
};